[package]
name = "card-service"
version = "0.1.0"
authors = ["James Daly <james@codenomads.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.2.0"
serde = "1.0.117"
